import LandingHeader from '@/components/LandingHeader/LandingHeader'
import './globals.scss'
import LandingFooter from '@/components/LandingFooter/LandingFooter'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body>
        <LandingHeader/>
        {children}
        <LandingFooter/>
      </body>
    </html>
  )
}
